name: loupe
base: core22
adopt-info: loupe
grade: stable
confinement: strict
compression: lzo

layout:
  /usr/share/loupe:
    symlink: $SNAP/usr/share/loupe
  /usr/libexec/glycin-loaders:
    bind: $SNAP/usr/libexec/glycin-loaders

parts:
  rustup:
    plugin: nil
    build-packages: [wget]
    build-environment:
      - RUSTUP_HOME: $CRAFT_PART_INSTALL/usr/share/rust
      - CARGO_HOME: $CRAFT_PART_INSTALL/usr/share/rust
      - CARGO_BUILD_JOBS: $CRAFT_PARALLEL_BUILD_COUNT
    override-pull: |
      wget https://sh.rustup.rs -O $CRAFT_PART_SRC/rustup-init.sh
      chmod +x $CRAFT_PART_SRC/rustup-init.sh
    override-build: |
      $CRAFT_PART_SRC/rustup-init.sh -y --no-modify-path
      mkdir -p $CRAFT_PART_INSTALL/usr/bin
      for i in `ls $RUSTUP_HOME/bin/`; do
        ln -s ../share/rust/bin/$i $CRAFT_PART_INSTALL/usr/bin/$i
      done
    override-prime: |
      echo 'Skip Prime'

  heif:
    source: https://github.com/strukturag/libheif.git
    source-tag: 'v1.14.2'
    source-depth: 1
    plugin: cmake
    cmake-parameters:
      - -DCMAKE_INSTALL_PREFIX=/usr
      - -Doptimization=3
      - -Ddebug=false
      
  glycin-loaders:
    after: [rustup, heif]
    plugin: meson
    source: https://download.gnome.org/sources/glycin-loaders/0.1/glycin-loaders-0.1.1.tar.xz
# ext:updatesnap
#   version-format:
#     ignore: true
    build-environment:
      - RUSTUP_HOME: $CRAFT_STAGE/usr/share/rust
      - CARGO_HOME: $CRAFT_STAGE/usr/share/rust
      - CARGO_BUILD_JOBS: $CRAFT_PARALLEL_BUILD_COUNT
    meson-parameters:
      - --prefix=/usr

  loupe:
    after: [ rustup, heif ]
    # See 'snapcraft plugins'
    plugin: meson
    source: https://gitlab.gnome.org/GNOME/loupe.git
    source-tag: '45.0'
    source-depth: 1
# ext:updatesnap
#   version-format:
#     lower-than: 46.0
    build-environment:
      - RUSTUP_HOME: $CRAFT_STAGE/usr/share/rust
      - CARGO_HOME: $CRAFT_STAGE/usr/share/rust
      - CARGO_BUILD_JOBS: $CRAFT_PARALLEL_BUILD_COUNT
    build-packages:
      - libyaml-dev
      - libxmlb-dev
    meson-parameters:
      - --prefix=/usr
      - -Doptimization=3
      - -Ddisable-glycin-sandbox=true
    parse-info: [ usr/share/metainfo/org.gnome.Loupe.metainfo.xml ]
    override-pull: |
      craftctl default
      sed -i.bak 's|2.12.0|2.12|g' meson.build

  libraries:
    plugin: nil
    stage-packages:
      - libx265-199
      - libde265-0
      - libdav1d5
      - libaom3
      - libnuma1
    prime:
      - usr/lib/*/lib*265.so.*
      - usr/lib/*/libdav1d.so.*
      - usr/lib/*/libaom.so.*
      - usr/lib/*/libnuma.so.*

slots:
  loupe:
    interface: dbus
    bus: session
    name: org.gnome.Loupe

apps:
  loupe:
    command: usr/bin/loupe
    desktop: usr/share/applications/org.gnome.Loupe.desktop
    extensions: [ gnome ]
    common-id: org.gnome.Loupe
    plugs:
      - process-control
      - home
